name: Publish to PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: arm64
      - uses: dtolnay/rust-toolchain@stable
      - run: scripts/setversion.sh ${{ github.ref_name }}
      - name: Build wheels - arm64
        uses: PyO3/maturin-action@v1
        with:
          target: aarch64-apple-darwin
          args: --release --out dist --sdist -m rust/Cargo.toml
      - name: Install built wheel - arm64
        run: |
          pip install "numpy<2"
          pip install exrio --no-dependencies --no-index --find-links dist --force-reinstall
          python -c "import exrio"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm64
          path: dist

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: ${{ matrix.target }}
      - uses: dtolnay/rust-toolchain@stable
      - run: scripts/setversion.sh ${{ github.ref_name }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -m rust/Cargo.toml
      - name: Install built wheel
        run: |
          pip install "numpy<2"
          pip install exrio --no-dependencies --no-index --find-links dist --force-reinstall
          python -c "import exrio"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.target }}
          path: dist

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - run: scripts/setversion.sh ${{ github.ref_name }}
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist -m rust/Cargo.toml
    - name: Install built wheel
      if: matrix.target == 'x86_64'
      run: |
        pip install "numpy<2"
        pip install exrio --no-dependencies --no-index --find-links dist --force-reinstall
        python -c "import exrio"
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux-${{ matrix.target }}
        path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ macos, windows, linux ]
    environment:
      name: pypi
      url: https://pypi.org/p/exrio
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download All Wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: True
      - name: Debug Directory Contents
        run: ls -l dist
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.whl
